# This is a basic workflow to help you get started with Actions

name: Newman Tests

on:
  workflow_dispatch:

jobs:
  newman_tests:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: install newman and reporters
      run: |
        npm install -g newman
        npm install -g newman-reporter-html
      
    - name: create 'newman' directory
      run: mkdir -p newman

    - name: run newman tests
      env:
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        BOOK_GLITCH_TESTS_COLLECTION_KEY: ${{env.BOOK_GLITCH_TESTS_COLLECTION_KEY}}
      run: |
        newman run "https://api.getpostman.com/collections/$BOOK_GLITCH_TESTS_COLLECTION_KEY?apikey=$POSTMAN_API_KEY" --environment "https://api.getpostman.com/environments/1975691-780421db-70ce-49de-9345-9d717c47aa4c?apikey=$POSTMAN_API_KEY" --reporters cli,html --reporter-html-export report.html --disable-unicode
      working-directory: newman
      
    - name: archive report
      uses: actions/upload-artifact@v3
      with:
        name: newman-report
        path: newman/*.html
