# This is a basic workflow to help you get started with Actions

name: Newman Tests

on:
  workflow_dispatch:

jobs:
  newman_tests:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: install newman and reporters
      run: |
        npm install -g newman
        npm install -g newman-reporter-html
        npm install -g newman-reporter-htmlextra
      
    - name: create 'newman' directory
      run: mkdir -p newman

    - name: run newman tests
      env:
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        BOOK_GLITCH_TESTS_COLLECTION_KEY: ${{secrets.BOOK_GLITCH_TESTS_COLLECTION_KEY}}
        BOOK_GLITCH_ENV : ${{secrets.BOOK_GLITCH_ENV}}
      run: |
        newman run "https://api.getpostman.com/collections/$BOOK_GLITCH_TESTS_COLLECTION_KEY?apikey=$POSTMAN_API_KEY" --environment "https://api.getpostman.com/environments/$BOOK_GLITCH_ENV?apikey=$POSTMAN_API_KEY" --reporters cli,html,htmlextra --reporter-html-export report.html --reporter-htmlextra-export htmlextra-report.html --disable-unicode
      working-directory: newman
      
    - name: archive report
      uses: actions/upload-artifact@v3
      with:
        name: newman-report
        path: newman/*.html
